---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# gitignore

<!-- badges: start -->
<!-- badges: end -->

The goal of gitignore is to ...

## Installation

You can install the released version of gitignore from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("gitignore")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
# devtools::install_github("pmassicotte/gitignore")
library(gitignore)

head(gitignore_fetch_available_templates(), 25)

```

Templates can be fecthed using the `gitignore_fetch_ignore()` function.

```{r, results='markup', comment=""}
gitignore_fetch_ignore("R")
```

Multiple templates can be fetched by specifying multiple values:

```{r, results='markup', comment=""}
gitignore_fetch_ignore(c("java", "c++"))
```

